services:
  app:
    container_name: "datachef-api"
    image: datachef-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - SPRING_PROFILES_ACTIVE=development
      - DB_HOST_DEV=${DB_HOST_DEV}
      - DB_PORT_DEV=${DB_PORT_DEV}
      - DB_NAME_DEV=${DB_NAME_DEV}
      - DB_USER_DEV=${DB_USER_DEV}
      - DB_PASSWORD_DEV=${DB_PASSWORD_DEV}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=86400000
      - MINIO_INTERNAL_ENDPOINT=${MINIO_INTERNAL_ENDPOINT}
      - MINIO_PUBLIC_ENDPOINT=${MINIO_PUBLIC_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET=${MINIO_BUCKET}
    env_file:
      - .env
    volumes:
      - maven-repo:/root/.m2
    depends_on:
      minio:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - datachef-network
    restart: unless-stopped

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - "9002:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - datachef-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/ready" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  minio-init:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: [ "/bin/sh", "/init.sh" ]
    environment:
      MINIO_ENDPOINT: ${MINIO_INTERNAL_ENDPOINT}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
      MINIO_BUCKET: ${MINIO_BUCKET}
    networks:
      - datachef-network
    volumes:
      - ./infra/minio/init.sh:/init.sh:ro
      - ./infra/minio/defaults:/defaults:ro

  postgres:
    image: 'postgres:latest'
    container_name: 'datachef-postgres'
    environment:
      - POSTGRES_DB=${DB_NAME_DEV}
      - POSTGRES_USER=${DB_USER_DEV}
      - POSTGRES_PASSWORD=${DB_PASSWORD_DEV}
    volumes:
      - postgres-data:/var/lib/postgresql
    networks:
      - datachef-network
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dev -d datachef" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

networks:
  datachef-network:
    driver: bridge

volumes:
  maven-repo:
  postgres-data:
    driver: local
  minio_data: